a = input('Digite algo:')
print('Ele é numérico?', a.isnumeric())
print('Ele é alfabético?', a.isalpha())
print('Ele é alfanumérico?', a.isalnum())
print('Ele tem espaços?', a.isspace())
print('Ele está maiusculo?', a.isupper())
print('Ele esta minusculo?', a.islower())
print('Ele esta captalizado?', a.istitle())
